#!/bin/bash
#SBATCH --job-name=DWIE_FINAL_R
#SBATCH --time=10:00:00
#SBATCH -N 1
## #SBATCH --ntasks-per-node=1
#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --gpus-per-task=4
#SBATCH --output=DWIE_FINAL_R.out
## in the list above, the partition name depends on where you are running your job. 
## On DAS5 the default would be `defq` on Lisa the default would be `gpu` or `gpu_shared`
## Typing `sinfo` on the server command line gives a column called PARTITION.  There, one can find the name of a specific node, the state (down, alloc, idle etc), the availability and how long is the ti$


# Load GPU drivers
## For Lisa modules are usually not needed, so remove the previous 2 lines. https://userinfo.surfsara.nl/systems/shared/modules 



# This loads the anaconda virtual environment with our packages
###export CUDA_VISIBLE_DEVICES=0,1,2,3

conda activate kg2Narrative

# Base directory for the experiment. This should be your outer folder, actually where this script is 
cd /home/tliberatore/KGNarrative


cols=('semantic_of_news' 'entities_list')
for element in "${cols[@]}"
do
    echo FINETUNIING_NOW_ON_$element
   python3 KGNarrative/script4trainingLLM/LED_4_DWIE.py KGNarrative/Datasets/DWIE/4experiment full $element led KGNarrative/FINAL_RESULTS/DWIE/$element --learning_rate 0.0001 --batch 1 --epochs 3
    echo DONE
done


