#!/bin/bash

cols=('semantic_of_news' 'entities_list')
for element in "${cols[@]}"
do
    echo FINETUNIING_NOW_ON_$element
   python3 KGNarrative/script4trainingLLM/LED_4_DWIE.py KGNarrative/Datasets/DWIE/4experiment full $element led KGNarrative/FINAL_RESULTS/DWIE/$element --learning_rate 0.0001 --batch 1 --epochs 3
    echo DONE
done


